[workspace]
# Publish both crates together
publish_no_verify = false

[[package]]
name = "mev-builders-macros"
# Publish the macro crate first since the main crate depends on it
publish_order = 1

[[package]]
name = "mev-builders" 
# Publish the main crate after the macro crate
publish_order = 2