name: Weekly Builder Order Update

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-builder-order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run aggregate stats script
        id: aggregate_stats
        run: |
          cd .github/scripts
          python aggregate_stats.py > ../../stats_output.txt
          echo "stats_output<<EOF" >> $GITHUB_OUTPUT
          cat ../../stats_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run code generation script
        run: |
          cd .github/scripts
          python gen_code.py

      - name: Format Rust code
        run: cargo fmt

      - name: Clean up temporary files
        run: |
          rm -f builder_aggregated.json

      - name: Check for changes
        id: check_changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are any changes
          if git diff --quiet; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check if changes are more than just comments
          # This checks for lines that don't start with # or // or /* or * or */
          if git diff --unified=0 | grep -E '^[\+\-]' | grep -v -E '^[\+\-][\+\-][\+\-]' | grep -E '^[\+\-][^#/\*\s]|^[\+\-]\s*[^#/\*\s]' | grep -v -E '^\+\s*\*|^\-\s*\*|^\+\s*\*/|^\-\s*\*/' > /dev/null; then
            echo "Substantial changes detected (more than comments)"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "Only comment changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: weekly builder order update"
          title: "chore: weekly builder order update"
          body: |
            ```
            ${{ steps.aggregate_stats.outputs.stats_output }}
            ```
          branch: weekly-builder-order-update
          delete-branch: true
          base: main
